-- MySQL Script generated by MySQL Workbench
-- 06/05/17 20:39:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RENDI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RENDI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RENDI` DEFAULT CHARACTER SET utf8 ;
USE `RENDI` ;

-- -----------------------------------------------------
-- Table `RENDI`.`estados_civis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`estados_civis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`funcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`funcoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`generos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`escolaridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`escolaridades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`setores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`funcionarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `end_cep` VARCHAR(8) NOT NULL,
  `end_uf` CHAR(2) NOT NULL,
  `end_cidade` VARCHAR(40) NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_rua` VARCHAR(60) NOT NULL,
  `end_numero` SMALLINT(4) UNSIGNED NOT NULL,
  `data_admissao` DATE NOT NULL,
  `data_demissao` DATE NULL,
  `data_nascimento` DATE NOT NULL,
  `salario` DOUBLE UNSIGNED NOT NULL,
  `foto` CHAR(45) NOT NULL DEFAULT 'usuario_padrao.png',
  `ativo` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `id_estado_civil` INT UNSIGNED NOT NULL,
  `id_funcao` INT UNSIGNED NOT NULL,
  `id_genero` INT UNSIGNED NOT NULL,
  `id_escolaridade` INT UNSIGNED NOT NULL,
  `id_setor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_estado_civil`, `id_funcao`, `id_genero`, `id_escolaridade`, `id_setor`),
  INDEX `fk_funcionarios_estados_civis1_idx` (`id_estado_civil` ASC),
  INDEX `fk_funcionarios_funcoes1_idx` (`id_funcao` ASC),
  INDEX `fk_funcionarios_generos1_idx` (`id_genero` ASC),
  INDEX `fk_funcionarios_escolaridades1_idx` (`id_escolaridade` ASC),
  INDEX `fk_funcionarios_setores1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_funcionarios_estados_civis1`
    FOREIGN KEY (`id_estado_civil`)
    REFERENCES `RENDI`.`estados_civis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_funcoes1`
    FOREIGN KEY (`id_funcao`)
    REFERENCES `RENDI`.`funcoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_generos1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `RENDI`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_escolaridades1`
    FOREIGN KEY (`id_escolaridade`)
    REFERENCES `RENDI`.`escolaridades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionarios_setores1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `RENDI`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(25) NOT NULL,
  `data` DATE NOT NULL,
  `ativo` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_funcionario`),
  INDEX `fk_usuarios_funcionarios_idx` (`id_funcionario` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_usuarios_funcionarios`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`clientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `end_cep` VARCHAR(8) NOT NULL,
  `end_uf` CHAR(2) NOT NULL,
  `end_cidade` VARCHAR(40) NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_rua` VARCHAR(60) NOT NULL,
  `end_numero` SMALLINT(4) UNSIGNED NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_genero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_genero`),
  INDEX `fk_clientes_generos1_idx` (`id_genero` ASC),
  CONSTRAINT `fk_clientes_generos1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `RENDI`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`funcionarios_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`funcionarios_telefones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_funcionario`),
  INDEX `fk_funcionarios_telefones_funcionarios1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_funcionarios_telefones_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`clientes_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`clientes_telefones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_cliente`),
  INDEX `fk_clientes_telefones_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_clientes_telefones_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `RENDI`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`unidades_medidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`unidades_medidas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`produtos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(70) NOT NULL,
  `preco` DOUBLE UNSIGNED NOT NULL,
  `quantidade` FLOAT UNSIGNED NOT NULL,
  `id_setor` INT UNSIGNED NOT NULL,
  `id_unidade_medida` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_setor`, `id_unidade_medida`, `id_funcionario`),
  INDEX `fk_produtos_setores1_idx` (`id_setor` ASC),
  INDEX `fk_produtos_unidades_medidas1_idx` (`id_unidade_medida` ASC),
  INDEX `fk_produtos_funcionarios1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_produtos_setores1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `RENDI`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_unidades_medidas1`
    FOREIGN KEY (`id_unidade_medida`)
    REFERENCES `RENDI`.`unidades_medidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`produtos_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`produtos_vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `unidades` SMALLINT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_produto`, `id_funcionario`, `id_cliente`),
  INDEX `fk_produtos_vendas_produtos1_idx` (`id_produto` ASC),
  INDEX `fk_produtos_vendas_funcionarios1_idx` (`id_funcionario` ASC),
  INDEX `fk_produtos_vendas_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_produtos_vendas_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `RENDI`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_vendas_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_vendas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `RENDI`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`fornecedores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `razao_social` VARCHAR(50) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `inscricao_estadual` VARCHAR(10) NOT NULL,
  `nome_fantasia` VARCHAR(50) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`fornecedores_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`fornecedores_telefones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `id_fornecedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_fornecedor`),
  INDEX `fk_fornecedores_telefones_fornecedores1_idx` (`id_fornecedor` ASC),
  CONSTRAINT `fk_fornecedores_telefones_fornecedores1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `RENDI`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`servicos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DOUBLE UNSIGNED NOT NULL,
  `id_setor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_setor`),
  INDEX `fk_servicos_setores1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_servicos_setores1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `RENDI`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`servicos_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`servicos_vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `placa` CHAR(8) NOT NULL,
  `quilometragem` DOUBLE UNSIGNED NULL,
  `id_servico` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_servico`, `id_funcionario`, `id_cliente`),
  INDEX `fk_servicos_vendas_servicos1_idx` (`id_servico` ASC),
  INDEX `fk_servicos_vendas_funcionarios1_idx` (`id_funcionario` ASC),
  INDEX `fk_servicos_vendas_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_servicos_vendas_servicos1`
    FOREIGN KEY (`id_servico`)
    REFERENCES `RENDI`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_vendas_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_vendas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `RENDI`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`tanques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`tanques` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `capacidade` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`bombas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`bombas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_tanque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_tanque`),
  INDEX `fk_bombas_tanques1_idx` (`id_tanque` ASC),
  CONSTRAINT `fk_bombas_tanques1`
    FOREIGN KEY (`id_tanque`)
    REFERENCES `RENDI`.`tanques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`combustiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`combustiveis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `preco` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`tanques_reparticoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`tanques_reparticoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_combustivel` INT UNSIGNED NOT NULL,
  `id_tanque` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_combustivel`, `id_tanque`),
  INDEX `fk_tanques_reparticoes_combustiveis1_idx` (`id_combustivel` ASC),
  INDEX `fk_tanques_reparticoes_tanques1_idx` (`id_tanque` ASC),
  CONSTRAINT `fk_tanques_reparticoes_combustiveis1`
    FOREIGN KEY (`id_combustivel`)
    REFERENCES `RENDI`.`combustiveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tanques_reparticoes_tanques1`
    FOREIGN KEY (`id_tanque`)
    REFERENCES `RENDI`.`tanques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`bicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`bicos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_bomba` INT UNSIGNED NOT NULL,
  `id_reparticao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_bomba`, `id_reparticao`),
  INDEX `fk_bicos_bombas1_idx` (`id_bomba` ASC),
  INDEX `fk_bicos_tanques_reparticoes1_idx` (`id_reparticao` ASC),
  CONSTRAINT `fk_bicos_bombas1`
    FOREIGN KEY (`id_bomba`)
    REFERENCES `RENDI`.`bombas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bicos_tanques_reparticoes1`
    FOREIGN KEY (`id_reparticao`)
    REFERENCES `RENDI`.`tanques_reparticoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`combustiveis_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`combustiveis_vendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `litros` FLOAT UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  `id_bico` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_cliente`, `id_funcionario`, `id_bico`),
  INDEX `fk_combustiveis_vendas_clientes1_idx` (`id_cliente` ASC),
  INDEX `fk_combustiveis_vendas_funcionarios1_idx` (`id_funcionario` ASC),
  INDEX `fk_combustiveis_vendas_bicos1_idx` (`id_bico` ASC),
  CONSTRAINT `fk_combustiveis_vendas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `RENDI`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combustiveis_vendas_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combustiveis_vendas_bicos1`
    FOREIGN KEY (`id_bico`)
    REFERENCES `RENDI`.`bicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`premios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`premios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(70) NOT NULL,
  `quantidade_pontos` INT UNSIGNED NOT NULL,
  `imagem` CHAR(37) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`fidelidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`fidelidades` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pontuacao` INT UNSIGNED NOT NULL DEFAULT 0,
  `id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_cliente`),
  INDEX `fk_fidelidades_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_fidelidades_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `RENDI`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`premiacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`premiacoes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `id_fidelidade` INT UNSIGNED NOT NULL,
  `id_premio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_fidelidade`, `id_premio`),
  INDEX `fk_premiacoes_premios1_idx` (`id_premio` ASC),
  INDEX `fk_premiacoes_fidelidades1_idx` (`id_fidelidade` ASC),
  CONSTRAINT `fk_premiacoes_premios1`
    FOREIGN KEY (`id_premio`)
    REFERENCES `RENDI`.`premios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_premiacoes_fidelidades1`
    FOREIGN KEY (`id_fidelidade`)
    REFERENCES `RENDI`.`fidelidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`orgaos_emissores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`orgaos_emissores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`licencas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`licencas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `anexo` VARCHAR(50) NOT NULL,
  `protocolo` VARCHAR(15) NOT NULL,
  `data_emissao` DATETIME NOT NULL,
  `data_vencimento` DATETIME NOT NULL,
  `id_orgao_emissor` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_orgao_emissor`, `id_funcionario`),
  UNIQUE INDEX `protocolo_UNIQUE` (`protocolo` ASC),
  INDEX `fk_licencas_orgaos_emissores1_idx` (`id_orgao_emissor` ASC),
  INDEX `fk_licencas_funcionarios1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_licencas_orgaos_emissores1`
    FOREIGN KEY (`id_orgao_emissor`)
    REFERENCES `RENDI`.`orgaos_emissores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licencas_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`tipos_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`tipos_pagamentos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`ordens_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`ordens_compra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `data_prevista` DATETIME NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL,
  `observacoes` TEXT NULL,
  `valor` DOUBLE UNSIGNED NOT NULL,
  `parcelas` SMALLINT(4) UNSIGNED NOT NULL,
  `distancia_pagamento` TINYINT(2) UNSIGNED NOT NULL,
  `id_fornecedor` INT UNSIGNED NOT NULL,
  `id_funcionario` INT UNSIGNED NOT NULL,
  `id_tipo_pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_fornecedor`, `id_funcionario`, `id_tipo_pagamento`),
  INDEX `fk_ordens_compra_fornecedores1_idx` (`id_fornecedor` ASC),
  INDEX `fk_ordens_compra_funcionarios1_idx` (`id_funcionario` ASC),
  INDEX `fk_ordens_compra_tipos_pagamentos1_idx` (`id_tipo_pagamento` ASC),
  CONSTRAINT `fk_ordens_compra_fornecedores1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `RENDI`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordens_compra_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `RENDI`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordens_compra_tipos_pagamentos1`
    FOREIGN KEY (`id_tipo_pagamento`)
    REFERENCES `RENDI`.`tipos_pagamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENDI`.`produtos_ordem_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENDI`.`produtos_ordem_compra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_ordem_compra` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_ordem_compra`, `id_produto`),
  INDEX `fk_produtos_ordem_compra_ordens_compra1_idx` (`id_ordem_compra` ASC),
  INDEX `fk_produtos_ordem_compra_produtos1_idx` (`id_produto` ASC),
  CONSTRAINT `fk_produtos_ordem_compra_ordens_compra1`
    FOREIGN KEY (`id_ordem_compra`)
    REFERENCES `RENDI`.`ordens_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_ordem_compra_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `RENDI`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
